/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\86191\\Desktop\\个人博客\\liang\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5fc33dca",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fc33dca").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-c7921c26",
    path: "/arithmetic/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c7921c26").then(next)
    },
  },
  {
    path: "/arithmetic/index.html",
    redirect: "/arithmetic/"
  },
  {
    name: "v-4b3cc4c3",
    path: "/dataStructure/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b3cc4c3").then(next)
    },
  },
  {
    path: "/dataStructure/index.html",
    redirect: "/dataStructure/"
  },
  {
    name: "v-552d4cab",
    path: "/interview/CSS/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-552d4cab").then(next)
    },
  },
  {
    name: "v-58bb7869",
    path: "/interview/CSS/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58bb7869").then(next)
    },
  },
  {
    name: "v-519f20ed",
    path: "/interview/CSS/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-519f20ed").then(next)
    },
  },
  {
    name: "v-5c49a427",
    path: "/interview/CSS/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c49a427").then(next)
    },
  },
  {
    name: "v-6365fba3",
    path: "/interview/CSS/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6365fba3").then(next)
    },
  },
  {
    name: "v-5fd7cfe5",
    path: "/interview/CSS/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fd7cfe5").then(next)
    },
  },
  {
    name: "v-6a82531f",
    path: "/interview/CSS/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a82531f").then(next)
    },
  },
  {
    name: "v-6e107edd",
    path: "/interview/CSS/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e107edd").then(next)
    },
  },
  {
    name: "v-66f42761",
    path: "/interview/CSS/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66f42761").then(next)
    },
  },
  {
    name: "v-876f7d9e",
    path: "/interview/CSS/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-876f7d9e").then(next)
    },
  },
  {
    name: "v-7936cea6",
    path: "/interview/CSS/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7936cea6").then(next)
    },
  },
  {
    name: "v-80532622",
    path: "/interview/CSS/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-80532622").then(next)
    },
  },
  {
    name: "v-63e1c832",
    path: "/interview/CSS/15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63e1c832").then(next)
    },
  },
  {
    name: "v-721a772a",
    path: "/interview/CSS/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-721a772a").then(next)
    },
  },
  {
    name: "v-6afe1fae",
    path: "/interview/CSS/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6afe1fae").then(next)
    },
  },
  {
    name: "v-55a9193a",
    path: "/interview/CSS/17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55a9193a").then(next)
    },
  },
  {
    name: "v-5cc570b6",
    path: "/interview/CSS/16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5cc570b6").then(next)
    },
  },
  {
    name: "v-4e8cc1be",
    path: "/interview/CSS/18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e8cc1be").then(next)
    },
  },
  {
    name: "v-47706a42",
    path: "/interview/CSS/19.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47706a42").then(next)
    },
  },
  {
    name: "v-2b6ca137",
    path: "/interview/ES6/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b6ca137").then(next)
    },
  },
  {
    name: "v-3288f8b3",
    path: "/interview/ES6/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3288f8b3").then(next)
    },
  },
  {
    name: "v-2a7f8d33",
    path: "/interview/CSS/20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a7f8d33").then(next)
    },
  },
  {
    name: "v-39a5502f",
    path: "/interview/ES6/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39a5502f").then(next)
    },
  },
  {
    name: "v-36172471",
    path: "/interview/ES6/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36172471").then(next)
    },
  },
  {
    name: "v-2efaccf5",
    path: "/interview/ES6/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2efaccf5").then(next)
    },
  },
  {
    name: "v-3d337bed",
    path: "/interview/ES6/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d337bed").then(next)
    },
  },
  {
    name: "v-0402a0ad",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0402a0ad").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    name: "v-40c1a7ab",
    path: "/interview/ES6/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40c1a7ab").then(next)
    },
  },
  {
    name: "v-444fd369",
    path: "/interview/ES6/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-444fd369").then(next)
    },
  },
  {
    name: "v-47ddff27",
    path: "/interview/ES6/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47ddff27").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]