/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\86191\\Desktop\\个人博客\\liang\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f7e447ec",
    path: "/AlgorithmsAndDataStructures/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f7e447ec").then(next)
    },
  },
  {
    name: "v-35b36f06",
    path: "/AlgorithmsAndDataStructures/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35b36f06").then(next)
    },
  },
  {
    name: "v-402bcb80",
    path: "/AlgorithmsAndDataStructures/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-402bcb80").then(next)
    },
  },
  {
    name: "v-e2f38ef8",
    path: "/AlgorithmsAndDataStructures/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e2f38ef8").then(next)
    },
  },
  {
    name: "v-314dfbfc",
    path: "/AlgorithmsAndDataStructures/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-314dfbfc").then(next)
    },
  },
  {
    name: "v-ce02d604",
    path: "/AlgorithmsAndDataStructures/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ce02d604").then(next)
    },
  },
  {
    name: "v-463eb4f0",
    path: "/AlgorithmsAndDataStructures/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-463eb4f0").then(next)
    },
  },
  {
    name: "v-65ea84a6",
    path: "/Algorithms/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65ea84a6").then(next)
    },
  },
  {
    path: "/Algorithms/index.html",
    redirect: "/Algorithms/"
  },
  {
    name: "v-1c5d4308",
    path: "/AlgorithmsAndDataStructures/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c5d4308").then(next)
    },
  },
  {
    name: "v-4aa427fa",
    path: "/AlgorithmsAndDataStructures/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4aa427fa").then(next)
    },
  },
  {
    name: "v-267d0e64",
    path: "/AlgorithmsAndDataStructures/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-267d0e64").then(next)
    },
  },
  {
    name: "v-4594424c",
    path: "/AlgorithmsAndDataStructures/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4594424c").then(next)
    },
  },
  {
    name: "v-118c5570",
    path: "/AlgorithmsAndDataStructures/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-118c5570").then(next)
    },
  },
  {
    name: "v-c331e86c",
    path: "/AlgorithmsAndDataStructures/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c331e86c").then(next)
    },
  },
  {
    name: "v-ae412f78",
    path: "/AlgorithmsAndDataStructures/15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ae412f78").then(next)
    },
  },
  {
    name: "v-01b231c2",
    path: "/AlgorithmsAndDataStructures/16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01b231c2").then(next)
    },
  },
  {
    name: "v-500c9ec6",
    path: "/AlgorithmsAndDataStructures/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-500c9ec6").then(next)
    },
  },
  {
    name: "v-5fc33dca",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fc33dca").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-99507684",
    path: "/AlgorithmsAndDataStructures/18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-99507684").then(next)
    },
  },
  {
    name: "v-08e01902",
    path: "/WebInterview/AdvanceInterview/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08e01902").then(next)
    },
  },
  {
    name: "v-04aa013d",
    path: "/WebInterview/AdvanceInterview/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04aa013d").then(next)
    },
  },
  {
    name: "v-5a84fb40",
    path: "/AlgorithmsAndDataStructures/17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a84fb40").then(next)
    },
  },
  {
    name: "v-0dc40efb",
    path: "/WebInterview/AdvanceInterview/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0dc40efb").then(next)
    },
  },
  {
    name: "v-16de1cb9",
    path: "/WebInterview/AdvanceInterview/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16de1cb9").then(next)
    },
  },
  {
    name: "v-434660ed",
    path: "/DataStructures/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-434660ed").then(next)
    },
  },
  {
    path: "/DataStructures/index.html",
    redirect: "/DataStructures/"
  },
  {
    name: "v-1ff82a77",
    path: "/WebInterview/AdvanceInterview/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ff82a77").then(next)
    },
  },
  {
    name: "v-29123835",
    path: "/WebInterview/AdvanceInterview/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29123835").then(next)
    },
  },
  {
    name: "v-322c45f3",
    path: "/WebInterview/AdvanceInterview/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-322c45f3").then(next)
    },
  },
  {
    name: "v-0c9d8fc3",
    path: "/WebInterview/AdvanceInterview/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c9d8fc3").then(next)
    },
  },
  {
    name: "v-1ed1ab3f",
    path: "/WebInterview/AdvanceInterview/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ed1ab3f").then(next)
    },
  },
  {
    name: "v-3b4653b1",
    path: "/WebInterview/AdvanceInterview/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b4653b1").then(next)
    },
  },
  {
    name: "v-3105c6bb",
    path: "/WebInterview/AdvanceInterview/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3105c6bb").then(next)
    },
  },
  {
    name: "v-4460616f",
    path: "/WebInterview/AdvanceInterview/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4460616f").then(next)
    },
  },
  {
    name: "v-15b79d81",
    path: "/WebInterview/AdvanceInterview/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15b79d81").then(next)
    },
  },
  {
    name: "v-2a6b7798",
    path: "/WebInterview/BasicsInterview/CSS/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a6b7798").then(next)
    },
  },
  {
    name: "v-6316add8",
    path: "/WebInterview/BasicsInterview/CSS/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6316add8").then(next)
    },
  },
  {
    name: "v-727dda90",
    path: "/WebInterview/BasicsInterview/CSS/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-727dda90").then(next)
    },
  },
  {
    name: "v-01276e10",
    path: "/WebInterview/BasicsInterview/CSS/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01276e10").then(next)
    },
  },
  {
    name: "v-c87c37d0",
    path: "/WebInterview/BasicsInterview/CSS/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c87c37d0").then(next)
    },
  },
  {
    name: "v-38177f38",
    path: "/WebInterview/BasicsInterview/CSS/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38177f38").then(next)
    },
  },
  {
    name: "v-0d185098",
    path: "/WebInterview/BasicsInterview/CSS/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d185098").then(next)
    },
  },
  {
    name: "v-27ebb8fd",
    path: "/WebInterview/AdvanceInterview/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27ebb8fd").then(next)
    },
  },
  {
    name: "v-5725cb50",
    path: "/WebInterview/BasicsInterview/CSS/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5725cb50").then(next)
    },
  },
  {
    name: "v-70c2b578",
    path: "/WebInterview/BasicsInterview/CSS/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70c2b578").then(next)
    },
  },
  {
    name: "v-7c73a558",
    path: "/WebInterview/BasicsInterview/CSS/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c73a558").then(next)
    },
  },
  {
    name: "v-95c248d0",
    path: "/WebInterview/BasicsInterview/CSS/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95c248d0").then(next)
    },
  },
  {
    name: "v-18c94078",
    path: "/WebInterview/BasicsInterview/CSS/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18c94078").then(next)
    },
  },
  {
    name: "v-246bdc50",
    path: "/WebInterview/BasicsInterview/CSS/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-246bdc50").then(next)
    },
  },
  {
    name: "v-517476b8",
    path: "/WebInterview/BasicsInterview/CSS/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-517476b8").then(next)
    },
  },
  {
    name: "v-ebc0a610",
    path: "/WebInterview/BasicsInterview/CSS/15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ebc0a610").then(next)
    },
  },
  {
    name: "v-26754818",
    path: "/WebInterview/BasicsInterview/CSS/16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26754818").then(next)
    },
  },
  {
    name: "v-7a6a3990",
    path: "/WebInterview/BasicsInterview/CSS/17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a6a3990").then(next)
    },
  },
  {
    name: "v-0913cd10",
    path: "/WebInterview/BasicsInterview/CSS/19.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0913cd10").then(next)
    },
  },
  {
    name: "v-2425e054",
    path: "/WebInterview/BasicsInterview/DesignPatterns/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2425e054").then(next)
    },
  },
  {
    name: "v-5f207e58",
    path: "/WebInterview/BasicsInterview/CSS/18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f207e58").then(next)
    },
  },
  {
    name: "v-6ad16e38",
    path: "/WebInterview/BasicsInterview/CSS/20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ad16e38").then(next)
    },
  },
  {
    name: "v-213ab4d6",
    path: "/WebInterview/BasicsInterview/DesignPatterns/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-213ab4d6").then(next)
    },
  },
  {
    name: "v-29fc3750",
    path: "/WebInterview/BasicsInterview/DesignPatterns/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29fc3750").then(next)
    },
  },
  {
    name: "v-2fd28e4c",
    path: "/WebInterview/BasicsInterview/DesignPatterns/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fd28e4c").then(next)
    },
  },
  {
    name: "v-27110bd2",
    path: "/WebInterview/BasicsInterview/DesignPatterns/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27110bd2").then(next)
    },
  },
  {
    name: "v-2ce762ce",
    path: "/WebInterview/BasicsInterview/DesignPatterns/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ce762ce").then(next)
    },
  },
  {
    name: "v-40598010",
    path: "/WebInterview/BasicsInterview/ES6/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40598010").then(next)
    },
  },
  {
    name: "v-9657dd50",
    path: "/WebInterview/BasicsInterview/ES6/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9657dd50").then(next)
    },
  },
  {
    name: "v-7c28db18",
    path: "/WebInterview/BasicsInterview/ES6/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c28db18").then(next)
    },
  },
  {
    name: "v-5129ac78",
    path: "/WebInterview/BasicsInterview/ES6/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5129ac78").then(next)
    },
  },
  {
    name: "v-187e7638",
    path: "/WebInterview/BasicsInterview/ES6/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-187e7638").then(next)
    },
  },
  {
    name: "v-250170d0",
    path: "/WebInterview/BasicsInterview/ES6/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-250170d0").then(next)
    },
  },
  {
    name: "v-ec563a90",
    path: "/WebInterview/BasicsInterview/ES6/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ec563a90").then(next)
    },
  },
  {
    name: "v-262a7dd8",
    path: "/WebInterview/BasicsInterview/ES6/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-262a7dd8").then(next)
    },
  },
  {
    name: "v-7affce10",
    path: "/WebInterview/BasicsInterview/ES6/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7affce10").then(next)
    },
  },
  {
    name: "v-6e8e0690",
    path: "/WebInterview/BasicsInterview/Git/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e8e0690").then(next)
    },
  },
  {
    name: "v-650e97d8",
    path: "/WebInterview/BasicsInterview/Git/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-650e97d8").then(next)
    },
  },
  {
    name: "v-016432f8",
    path: "/WebInterview/BasicsInterview/Git/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-016432f8").then(next)
    },
  },
  {
    name: "v-5335f750",
    path: "/WebInterview/BasicsInterview/Git/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5335f750").then(next)
    },
  },
  {
    name: "v-c48c63d0",
    path: "/WebInterview/BasicsInterview/Git/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c48c63d0").then(next)
    },
  },
  {
    name: "v-3a0f6938",
    path: "/WebInterview/BasicsInterview/Git/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a0f6938").then(next)
    },
  },
  {
    name: "v-72ba9f78",
    path: "/WebInterview/BasicsInterview/Git/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72ba9f78").then(next)
    },
  },
  {
    name: "v-02312166",
    path: "/WebInterview/BasicsInterview/Js/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02312166").then(next)
    },
  },
  {
    name: "v-0f103a98",
    path: "/WebInterview/BasicsInterview/Git/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f103a98").then(next)
    },
  },
  {
    name: "v-1ac12a78",
    path: "/WebInterview/BasicsInterview/Git/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ac12a78").then(next)
    },
  },
  {
    name: "v-725b3938",
    path: "/WebInterview/BasicsInterview/Js/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-725b3938").then(next)
    },
  },
  {
    name: "v-a9345490",
    path: "/WebInterview/BasicsInterview/Git/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9345490").then(next)
    },
  },
  {
    name: "v-5014e760",
    path: "/WebInterview/BasicsInterview/Js/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5014e760").then(next)
    },
  },
  {
    name: "v-14b6295e",
    path: "/WebInterview/BasicsInterview/Js/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14b6295e").then(next)
    },
  },
  {
    name: "v-e918b53c",
    path: "/WebInterview/BasicsInterview/Js/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e918b53c").then(next)
    },
  },
  {
    name: "v-4d512948",
    path: "/WebInterview/BasicsInterview/Js/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d512948").then(next)
    },
  },
  {
    name: "v-6299ef58",
    path: "/WebInterview/BasicsInterview/Js/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6299ef58").then(next)
    },
  },
  {
    name: "v-c40ea54c",
    path: "/WebInterview/BasicsInterview/Js/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c40ea54c").then(next)
    },
  },
  {
    name: "v-273b3156",
    path: "/WebInterview/BasicsInterview/Js/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-273b3156").then(next)
    },
  },
  {
    name: "v-0d16dd2a",
    path: "/WebInterview/BasicsInterview/Js/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d16dd2a").then(next)
    },
  },
  {
    name: "v-5c8fc1b0",
    path: "/WebInterview/BasicsInterview/Js/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c8fc1b0").then(next)
    },
  },
  {
    name: "v-d34d3db4",
    path: "/WebInterview/BasicsInterview/Js/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d34d3db4").then(next)
    },
  },
  {
    name: "v-5afaa324",
    path: "/WebInterview/BasicsInterview/Js/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5afaa324").then(next)
    },
  },
  {
    name: "v-1f9be522",
    path: "/WebInterview/BasicsInterview/Js/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f9be522").then(next)
    },
  },
  {
    name: "v-3785b1c0",
    path: "/WebInterview/BasicsInterview/Js/15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3785b1c0").then(next)
    },
  },
  {
    name: "v-127ba1d0",
    path: "/WebInterview/BasicsInterview/Js/19.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-127ba1d0").then(next)
    },
  },
  {
    name: "v-46c44a28",
    path: "/WebInterview/BasicsInterview/Js/20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46c44a28").then(next)
    },
  },
  {
    name: "v-3220ed1a",
    path: "/WebInterview/BasicsInterview/Js/18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3220ed1a").then(next)
    },
  },
  {
    name: "v-bd81c62c",
    path: "/WebInterview/BasicsInterview/Js/21.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd81c62c").then(next)
    },
  },
  {
    name: "v-ae432dc4",
    path: "/WebInterview/BasicsInterview/Js/16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ae432dc4").then(next)
    },
  },
  {
    name: "v-65e05ee8",
    path: "/WebInterview/BasicsInterview/Js/22.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65e05ee8").then(next)
    },
  },
  {
    name: "v-21ba3a38",
    path: "/WebInterview/BasicsInterview/Js/24.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21ba3a38").then(next)
    },
  },
  {
    name: "v-9877b63c",
    path: "/WebInterview/BasicsInterview/Js/25.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9877b63c").then(next)
    },
  },
  {
    name: "v-2a81a0e6",
    path: "/WebInterview/BasicsInterview/Js/23.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a81a0e6").then(next)
    },
  },
  {
    name: "v-6d7fab1c",
    path: "/WebInterview/BasicsInterview/Js/17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d7fab1c").then(next)
    },
  },
  {
    name: "v-786566e0",
    path: "/WebInterview/BasicsInterview/Js/26.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-786566e0").then(next)
    },
  },
  {
    name: "v-736da64c",
    path: "/WebInterview/BasicsInterview/Js/29.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-736da64c").then(next)
    },
  },
  {
    name: "v-01a7eadc",
    path: "/WebInterview/BasicsInterview/Js/28.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01a7eadc").then(next)
    },
  },
  {
    name: "v-3d06a8de",
    path: "/WebInterview/BasicsInterview/Js/27.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d06a8de").then(next)
    },
  },
  {
    name: "v-70c61aac",
    path: "/WebInterview/BasicsInterview/Js/31.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70c61aac").then(next)
    },
  },
  {
    name: "v-a7b64ea4",
    path: "/WebInterview/BasicsInterview/Js/30.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7b64ea4").then(next)
    },
  },
  {
    name: "v-35675caa",
    path: "/WebInterview/BasicsInterview/Js/32.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35675caa").then(next)
    },
  },
  {
    name: "v-0beec2b0",
    path: "/WebInterview/BasicsInterview/Js/33.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0beec2b0").then(next)
    },
  },
  {
    name: "v-4f09ac78",
    path: "/WebInterview/BasicsInterview/Linux/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f09ac78").then(next)
    },
  },
  {
    name: "v-82ac3eb4",
    path: "/WebInterview/BasicsInterview/Js/34.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82ac3eb4").then(next)
    },
  },
  {
    name: "v-96d2add0",
    path: "/WebInterview/BasicsInterview/Linux/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-96d2add0").then(next)
    },
  },
  {
    name: "v-738ea950",
    path: "/WebInterview/BasicsInterview/Linux/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-738ea950").then(next)
    },
  },
  {
    name: "v-3d67aa38",
    path: "/WebInterview/BasicsInterview/Linux/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d67aa38").then(next)
    },
  },
  {
    name: "v-2bc5a7f8",
    path: "/WebInterview/BasicsInterview/Linux/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bc5a7f8").then(next)
    },
  },
  {
    name: "v-ba16b250",
    path: "/WebInterview/BasicsInterview/Linux/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba16b250").then(next)
    },
  },
  {
    name: "v-1a23a5b8",
    path: "/WebInterview/BasicsInterview/Linux/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a23a5b8").then(next)
    },
  },
  {
    name: "v-0fa47538",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fa47538").then(next)
    },
  },
  {
    name: "v-36ed56d8",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36ed56d8").then(next)
    },
  },
  {
    name: "v-5e363878",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e363878").then(next)
    },
  },
  {
    name: "v-f501cbd0",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f501cbd0").then(next)
    },
  },
  {
    name: "v-a6700890",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6700890").then(next)
    },
  },
  {
    name: "v-57de4550",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57de4550").then(next)
    },
  },
  {
    name: "v-094c8210",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-094c8210").then(next)
    },
  },
  {
    name: "v-22a2a098",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22a2a098").then(next)
    },
  },
  {
    name: "v-49eb8238",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49eb8238").then(next)
    },
  },
  {
    name: "v-0e7ead90",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e7ead90").then(next)
    },
  },
  {
    name: "v-aba23410",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aba23410").then(next)
    },
  },
  {
    name: "v-5d1070d0",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d1070d0").then(next)
    },
  },
  {
    name: "v-6e9b4e18",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e9b4e18").then(next)
    },
  },
  {
    name: "v-20098ad8",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20098ad8").then(next)
    },
  },
  {
    name: "v-296b2398",
    path: "/WebInterview/BasicsInterview/Node/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-296b2398").then(next)
    },
  },
  {
    name: "v-47526c78",
    path: "/WebInterview/BasicsInterview/NetworkProtocol/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47526c78").then(next)
    },
  },
  {
    name: "v-c0781fd8",
    path: "/WebInterview/BasicsInterview/Node/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c0781fd8").then(next)
    },
  },
  {
    name: "v-161cbc90",
    path: "/WebInterview/BasicsInterview/Node/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-161cbc90").then(next)
    },
  },
  {
    name: "v-5af05652",
    path: "/WebInterview/BasicsInterview/Node/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5af05652").then(next)
    },
  },
  {
    name: "v-5d6dba64",
    path: "/WebInterview/BasicsInterview/Node/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d6dba64").then(next)
    },
  },
  {
    name: "v-36d0ec54",
    path: "/WebInterview/BasicsInterview/Node/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36d0ec54").then(next)
    },
  },
  {
    name: "v-e714ede8",
    path: "/WebInterview/BasicsInterview/Node/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e714ede8").then(next)
    },
  },
  {
    name: "v-47a1ef4a",
    path: "/WebInterview/BasicsInterview/Node/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47a1ef4a").then(next)
    },
  },
  {
    name: "v-02ce5588",
    path: "/WebInterview/BasicsInterview/Node/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02ce5588").then(next)
    },
  },
  {
    name: "v-5868f5cc",
    path: "/WebInterview/BasicsInterview/Node/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5868f5cc").then(next)
    },
  },
  {
    name: "v-189f1edc",
    path: "/WebInterview/BasicsInterview/Node/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-189f1edc").then(next)
    },
  },
  {
    name: "v-e2102950",
    path: "/WebInterview/BasicsInterview/Node/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e2102950").then(next)
    },
  },
  {
    name: "v-4a245196",
    path: "/WebInterview/BasicsInterview/Node/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a245196").then(next)
    },
  },
  {
    name: "v-0550b7d4",
    path: "/WebInterview/BasicsInterview/Node/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0550b7d4").then(next)
    },
  },
  {
    name: "v-4f435ac6",
    path: "/WebInterview/BasicsInterview/Pack/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f435ac6").then(next)
    },
  },
  {
    name: "v-3bf4f3be",
    path: "/WebInterview/BasicsInterview/Pack/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bf4f3be").then(next)
    },
  },
  {
    name: "v-0a6fc104",
    path: "/WebInterview/BasicsInterview/Pack/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a6fc104").then(next)
    },
  },
  {
    name: "v-74c7b17c",
    path: "/WebInterview/BasicsInterview/Pack/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74c7b17c").then(next)
    },
  },
  {
    name: "v-fe6ee500",
    path: "/WebInterview/BasicsInterview/Pack/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe6ee500").then(next)
    },
  },
  {
    name: "v-11bd4c08",
    path: "/WebInterview/BasicsInterview/Pack/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11bd4c08").then(next)
    },
  },
  {
    name: "v-28a68cb6",
    path: "/WebInterview/BasicsInterview/Pack/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28a68cb6").then(next)
    },
  },
  {
    name: "v-6d7a2678",
    path: "/WebInterview/BasicsInterview/Pack/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d7a2678").then(next)
    },
  },
  {
    name: "v-9b647f8c",
    path: "/WebInterview/BasicsInterview/Pack/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b647f8c").then(next)
    },
  },
  {
    name: "v-3e77560a",
    path: "/WebInterview/BasicsInterview/Pack/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e77560a").then(next)
    },
  },
  {
    name: "v-8411b890",
    path: "/WebInterview/BasicsInterview/React/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8411b890").then(next)
    },
  },
  {
    name: "v-a755bd10",
    path: "/WebInterview/BasicsInterview/React/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a755bd10").then(next)
    },
  },
  {
    name: "v-35262298",
    path: "/WebInterview/BasicsInterview/React/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35262298").then(next)
    },
  },
  {
    name: "v-46c824d8",
    path: "/WebInterview/BasicsInterview/React/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46c824d8").then(next)
    },
  },
  {
    name: "v-23842058",
    path: "/WebInterview/BasicsInterview/React/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23842058").then(next)
    },
  },
  {
    name: "v-ca99c190",
    path: "/WebInterview/BasicsInterview/React/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ca99c190").then(next)
    },
  },
  {
    name: "v-11e21e18",
    path: "/WebInterview/BasicsInterview/React/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11e21e18").then(next)
    },
  },
  {
    name: "v-00401bd8",
    path: "/WebInterview/BasicsInterview/React/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00401bd8").then(next)
    },
  },
  {
    name: "v-edddc610",
    path: "/WebInterview/BasicsInterview/React/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edddc610").then(next)
    },
  },
  {
    name: "v-2ca800d8",
    path: "/WebInterview/BasicsInterview/React/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ca800d8").then(next)
    },
  },
  {
    name: "v-950dfc10",
    path: "/WebInterview/BasicsInterview/React/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-950dfc10").then(next)
    },
  },
  {
    name: "v-3e4a0318",
    path: "/WebInterview/BasicsInterview/React/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e4a0318").then(next)
    },
  },
  {
    name: "v-b8520090",
    path: "/WebInterview/BasicsInterview/React/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b8520090").then(next)
    },
  },
  {
    name: "v-1b05fe98",
    path: "/WebInterview/BasicsInterview/React/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b05fe98").then(next)
    },
  },
  {
    name: "v-feda0990",
    path: "/WebInterview/BasicsInterview/React/17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-feda0990").then(next)
    },
  },
  {
    name: "v-db960510",
    path: "/WebInterview/BasicsInterview/React/15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db960510").then(next)
    },
  },
  {
    name: "v-0963fc58",
    path: "/WebInterview/BasicsInterview/React/16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0963fc58").then(next)
    },
  },
  {
    name: "v-107c0bd0",
    path: "/WebInterview/BasicsInterview/React/18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-107c0bd0").then(next)
    },
  },
  {
    name: "v-6ef0f8f8",
    path: "/WebInterview/BasicsInterview/React/19.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ef0f8f8").then(next)
    },
  },
  {
    name: "v-2429df18",
    path: "/WebInterview/BasicsInterview/React/21.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2429df18").then(next)
    },
  },
  {
    name: "v-a60a3f90",
    path: "/WebInterview/BasicsInterview/React/20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a60a3f90").then(next)
    },
  },
  {
    name: "v-c94e4410",
    path: "/WebInterview/BasicsInterview/React/22.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c94e4410").then(next)
    },
  },
  {
    name: "v-1287dcd8",
    path: "/WebInterview/BasicsInterview/React/23.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1287dcd8").then(next)
    },
  },
  {
    name: "v-ec924890",
    path: "/WebInterview/BasicsInterview/React/24.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ec924890").then(next)
    },
  },
  {
    name: "v-7814d978",
    path: "/WebInterview/BasicsInterview/React/26.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7814d978").then(next)
    },
  },
  {
    name: "v-00e5da98",
    path: "/WebInterview/BasicsInterview/React/25.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00e5da98").then(next)
    },
  },
  {
    name: "v-21784f50",
    path: "/WebInterview/BasicsInterview/React/27.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21784f50").then(next)
    },
  },
  {
    name: "v-44bc53d0",
    path: "/WebInterview/BasicsInterview/React/29.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44bc53d0").then(next)
    },
  },
  {
    name: "v-6672d738",
    path: "/WebInterview/BasicsInterview/React/28.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6672d738").then(next)
    },
  },
  {
    name: "v-1babbd58",
    path: "/WebInterview/BasicsInterview/React/30.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1babbd58").then(next)
    },
  },
  {
    name: "v-da4a8790",
    path: "/WebInterview/BasicsInterview/React/31.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da4a8790").then(next)
    },
  },
  {
    name: "v-fd8e8c10",
    path: "/WebInterview/BasicsInterview/React/33.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fd8e8c10").then(next)
    },
  },
  {
    name: "v-0a09bb18",
    path: "/WebInterview/BasicsInterview/React/32.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a09bb18").then(next)
    },
  },
  {
    name: "v-68ebe3da",
    path: "/WebInterview/BasicsInterview/Typescript/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68ebe3da").then(next)
    },
  },
  {
    name: "v-395e70dc",
    path: "/WebInterview/BasicsInterview/Typescript/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-395e70dc").then(next)
    },
  },
  {
    name: "v-09d0fdde",
    path: "/WebInterview/BasicsInterview/Typescript/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09d0fdde").then(next)
    },
  },
  {
    name: "v-cf0d5250",
    path: "/WebInterview/BasicsInterview/Typescript/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf0d5250").then(next)
    },
  },
  {
    name: "v-6ff26c54",
    path: "/WebInterview/BasicsInterview/Typescript/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ff26c54").then(next)
    },
  },
  {
    name: "v-2721afd2",
    path: "/WebInterview/BasicsInterview/Typescript/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2721afd2").then(next)
    },
  },
  {
    name: "v-10d78658",
    path: "/WebInterview/BasicsInterview/Typescript/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10d78658").then(next)
    },
  },
  {
    name: "v-f386d464",
    path: "/WebInterview/BasicsInterview/Typescript/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f386d464").then(next)
    },
  },
  {
    name: "v-56af22d0",
    path: "/WebInterview/BasicsInterview/Typescript/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56af22d0").then(next)
    },
  },
  {
    name: "v-c73710bc",
    path: "/WebInterview/BasicsInterview/Typescript/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c73710bc").then(next)
    },
  },
  {
    name: "v-681c2ac0",
    path: "/WebInterview/BasicsInterview/Typescript/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-681c2ac0").then(next)
    },
  },
  {
    name: "v-3ebdf078",
    path: "/WebInterview/BasicsInterview/Vue/03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ebdf078").then(next)
    },
  },
  {
    name: "v-090144c4",
    path: "/WebInterview/BasicsInterview/Typescript/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-090144c4").then(next)
    },
  },
  {
    name: "v-0612ba38",
    path: "/WebInterview/BasicsInterview/Vue/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0612ba38").then(next)
    },
  },
  {
    name: "v-bb2f5550",
    path: "/WebInterview/BasicsInterview/Vue/02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bb2f5550").then(next)
    },
  },
  {
    name: "v-49d8e8d0",
    path: "/WebInterview/BasicsInterview/Vue/04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49d8e8d0").then(next)
    },
  },
  {
    name: "v-776926b8",
    path: "/WebInterview/BasicsInterview/Vue/05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-776926b8").then(next)
    },
  },
  {
    name: "v-13bec1d8",
    path: "/WebInterview/BasicsInterview/Vue/06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13bec1d8").then(next)
    },
  },
  {
    name: "v-9fd74610",
    path: "/WebInterview/BasicsInterview/Vue/07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9fd74610").then(next)
    },
  },
  {
    name: "v-4c69f818",
    path: "/WebInterview/BasicsInterview/Vue/08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c69f818").then(next)
    },
  },
  {
    name: "v-2e80d990",
    path: "/WebInterview/BasicsInterview/Vue/09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e80d990").then(next)
    },
  },
  {
    name: "v-581ae7f8",
    path: "/WebInterview/BasicsInterview/Vue/10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-581ae7f8").then(next)
    },
  },
  {
    name: "v-2d1bb958",
    path: "/WebInterview/BasicsInterview/Vue/13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d1bb958").then(next)
    },
  },
  {
    name: "v-de73c390",
    path: "/WebInterview/BasicsInterview/Vue/12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de73c390").then(next)
    },
  },
  {
    name: "v-171ef9d0",
    path: "/WebInterview/BasicsInterview/Vue/11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-171ef9d0").then(next)
    },
  },
  {
    name: "v-6d1d5710",
    path: "/WebInterview/BasicsInterview/Vue/14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d1d5710").then(next)
    },
  },
  {
    name: "v-65c6ef98",
    path: "/WebInterview/BasicsInterview/Vue/15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65c6ef98").then(next)
    },
  },
  {
    name: "v-c31bb450",
    path: "/WebInterview/BasicsInterview/Vue/17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c31bb450").then(next)
    },
  },
  {
    name: "v-021c8ab8",
    path: "/WebInterview/BasicsInterview/Vue/16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-021c8ab8").then(next)
    },
  },
  {
    name: "v-3ac7c0f8",
    path: "/WebInterview/BasicsInterview/Vue/18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ac7c0f8").then(next)
    },
  },
  {
    name: "v-4678b0d8",
    path: "/WebInterview/BasicsInterview/Vue/20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4678b0d8").then(next)
    },
  },
  {
    name: "v-51c547d0",
    path: "/WebInterview/BasicsInterview/Vue/19.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51c547d0").then(next)
    },
  },
  {
    name: "v-3a636810",
    path: "/WebInterview/BasicsInterview/Vue/21.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a636810").then(next)
    },
  },
  {
    name: "v-7f23e718",
    path: "/WebInterview/BasicsInterview/Vue/22.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f23e718").then(next)
    },
  },
  {
    name: "v-5424b878",
    path: "/WebInterview/BasicsInterview/Vue/25.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5424b878").then(next)
    },
  },
  {
    name: "v-9061c550",
    path: "/WebInterview/BasicsInterview/Vue/24.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9061c550").then(next)
    },
  },
  {
    name: "v-1b798238",
    path: "/WebInterview/BasicsInterview/Vue/23.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b798238").then(next)
    },
  },
  {
    name: "v-1f0b58d0",
    path: "/WebInterview/BasicsInterview/Vue/26.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f0b58d0").then(next)
    },
  },
  {
    name: "v-e6602290",
    path: "/WebInterview/BasicsInterview/Vue/27.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6602290").then(next)
    },
  },
  {
    name: "v-7509b610",
    path: "/WebInterview/BasicsInterview/Vue/29.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7509b610").then(next)
    },
  },
  {
    name: "v-34d679b8",
    path: "/WebInterview/BasicsInterview/Vue/30.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34d679b8").then(next)
    },
  },
  {
    name: "v-292589d8",
    path: "/WebInterview/BasicsInterview/Vue/28.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-292589d8").then(next)
    },
  },
  {
    name: "v-5da7d650",
    path: "/WebInterview/BasicsInterview/Vue/31.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5da7d650").then(next)
    },
  },
  {
    name: "v-6d81aff8",
    path: "/WebInterview/BasicsInterview/Vue/32.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d81aff8").then(next)
    },
  },
  {
    name: "v-09d74b18",
    path: "/WebInterview/BasicsInterview/Vue/33.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09d74b18").then(next)
    },
  },
  {
    name: "v-b3a63390",
    path: "/WebInterview/BasicsInterview/Vue/34.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3a63390").then(next)
    },
  },
  {
    name: "v-42828158",
    path: "/WebInterview/BasicsInterview/Vue/35.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42828158").then(next)
    },
  },
  {
    name: "v-7b2db798",
    path: "/WebInterview/BasicsInterview/Vue/37.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b2db798").then(next)
    },
  },
  {
    name: "v-424fc710",
    path: "/WebInterview/BasicsInterview/Vue/36.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-424fc710").then(next)
    },
  },
  {
    name: "v-178352b8",
    path: "/WebInterview/BasicsInterview/Vue/38.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-178352b8").then(next)
    },
  },
  {
    name: "v-6f31c0ba",
    path: "/project/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f31c0ba").then(next)
    },
  },
  {
    path: "/project/index.html",
    redirect: "/project/"
  },
  {
    name: "v-ba2d839a",
    path: "/utils/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba2d839a").then(next)
    },
  },
  {
    path: "/utils/index.html",
    redirect: "/utils/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]